ExpediaGroup/beekeeper

beekeeper-cleanup/pom.xml, beekeeper-core/pom.xml, beekeeper-integration-tests/pom.xml, beekeeper-package/beekeeper-assembly-cleanup/pom.xml, beekeeper-package/beekeeper-assembly-path-scheduler-apiary/pom.xml, beekeeper-package/pom.xml, beekeeper-path-scheduler-apiary/pom.xml, pom.xml
I've removed `cobertura-maven-plugin` since this is not in `eg-oss-plugin`'s dependencies (it was added for making it work with `hotels-oss-plugin`) :)
=> Update pom parent and scm details

CHANGELOG.md, Jenkinsfile, beekeeper-package/beekeeper-assembly-cleanup/pom.xml, beekeeper-package/beekeeper-assembly-cleanup/src/main/docker/Dockerfile, beekeeper-package/beekeeper-assembly-path-scheduler-apiary/pom.xml, beekeeper-package/beekeeper-assembly-path-scheduler-apiary/src/main/docker/Dockerfile, beekeeper-package/pom.xml, pom.xml
Reopening this PR for the open source build.
Will squash when merging so we don't have all these testing commits.
=> Oss docker build

CHANGELOG.md
=> Prepping for release

CHANGELOG.md, Jenkinsfile, README.md, grafana-model.json, pom.xml
Opening a PR to refresh the README and make some small updates to the Jenkinsfile
=> Os refresh

CHANGELOG.md, README.md, beekeeper-core/pom.xml, beekeeper-integration-tests/pom.xml, beekeeper-integration-tests/src/test/java/com/expediagroup/beekeeper/integration/BeekeeperCleanupIntegrationTest.java, beekeeper-integration-tests/src/test/java/com/expediagroup/beekeeper/integration/BeekeeperDryRunCleanupIntegrationTest.java, beekeeper-integration-tests/src/test/java/com/expediagroup/beekeeper/integration/BeekeeperPathSchedulerApiaryIntegrationTest.java, beekeeper-path-scheduler-apiary/pom.xml
PR to add health check endpoints to Beekeeper
Endpoints will be at Spring's default location: `/actuator/health`
=> Add health endpoint

beekeeper-cleanup/src/main/java/com/expediagroup/beekeeper/cleanup/BeekeeperCleanup.java
=> Updating bean name

CHANGELOG.md
=> Changing release date

beekeeper-core/src/main/java/com/expediagroup/beekeeper/core/monitoring/TimedTaggableAspect.java
=> Adding license for timed taggable

beekeeper-cleanup/src/main/java/com/expediagroup/beekeeper/cleanup/monitoring/BytesDeletedReporter.java
This was removed in a previous PR but is actually quite useful.
=> Adding logs

CHANGELOG.md, beekeeper-cleanup/src/main/java/com/expediagroup/beekeeper/cleanup/context/CommonBeans.java, beekeeper-cleanup/src/main/java/com/expediagroup/beekeeper/cleanup/monitoring/BytesDeletedReporter.java, beekeeper-cleanup/src/main/java/com/expediagroup/beekeeper/cleanup/path/aws/S3BytesDeletedCalculator.java, beekeeper-cleanup/src/main/java/com/expediagroup/beekeeper/cleanup/path/aws/S3Client.java, beekeeper-cleanup/src/main/java/com/expediagroup/beekeeper/cleanup/path/aws/S3PathCleaner.java, beekeeper-cleanup/src/main/java/com/expediagroup/beekeeper/cleanup/path/aws/S3SchemeURI.java, beekeeper-cleanup/src/main/java/com/expediagroup/beekeeper/cleanup/path/aws/S3SentinelFilesCleaner.java, beekeeper-cleanup/src/test/java/com/expediagroup/beekeeper/cleanup/TestApplication.java, beekeeper-cleanup/src/test/java/com/expediagroup/beekeeper/cleanup/context/CommonBeansTest.java, beekeeper-cleanup/src/test/java/com/expediagroup/beekeeper/cleanup/monitoring/BytesDeletedReporterTest.java, beekeeper-cleanup/src/test/java/com/expediagroup/beekeeper/cleanup/path/aws/AmazonS3Factory.java, beekeeper-cleanup/src/test/java/com/expediagroup/beekeeper/cleanup/path/aws/S3BytesDeletedCalculatorTest.java, beekeeper-cleanup/src/test/java/com/expediagroup/beekeeper/cleanup/path/aws/S3ClientTest.java, beekeeper-cleanup/src/test/java/com/expediagroup/beekeeper/cleanup/path/aws/S3DryRunPathCleanerTest.java, beekeeper-cleanup/src/test/java/com/expediagroup/beekeeper/cleanup/path/aws/S3PathCleanerTest.java, beekeeper-cleanup/src/test/java/com/expediagroup/beekeeper/cleanup/path/aws/S3SchemeURITest.java, beekeeper-cleanup/src/test/java/com/expediagroup/beekeeper/cleanup/path/aws/S3SentinelFilesCleanerTest.java, beekeeper-cleanup/src/test/java/com/expediagroup/beekeeper/cleanup/service/PagingCleanupServiceTest.java, beekeeper-cleanup/src/test/resources/logback-test.xml, beekeeper-core/src/main/java/com/expediagroup/beekeeper/core/config/FileSystemType.java, beekeeper-core/src/main/java/com/expediagroup/beekeeper/core/model/EntityHousekeepingPath.java, beekeeper-core/src/main/java/com/expediagroup/beekeeper/core/model/HousekeepingPath.java, beekeeper-integration-tests/src/test/java/com/expediagroup/beekeeper/integration/BeekeeperCleanupIntegrationTest.java, beekeeper-integration-tests/src/test/java/com/expediagroup/beekeeper/integration/BeekeeperDryRunCleanupIntegrationTest.java, beekeeper-path-scheduler-apiary/src/main/java/com/expediagroup/beekeeper/scheduler/apiary/filter/WhitelistedListenerEventFilter.java, beekeeper-path-scheduler-apiary/src/test/java/com/expediagroup/beekeeper/scheduler/filter/WhitelistedListenerEventFilterTest.java
Updating copyrights to perform release
=> Prep for release

CHANGELOG.md, pom.xml
- upgrade junit to 5.6.0 (and import bom)
- upgrade mockito to 3.2.4
- removed override of surefire
=> Get tests running in Eclipse and fix Travis

.github/workflows/main.yml, pom.xml
Added GH actions to account for possible resource based issues being shown in Travis runs
Results of run: https://github.com/KenFigueiredo/beekeeper/runs/403609775
=> Add GH Actions for Beekeeper

README.md, beekeeper-cleanup/src/main/java/com/expediagroup/beekeeper/cleanup/BeekeeperCleanup.java, beekeeper-core/src/main/java/com/expediagroup/beekeeper/core/config/PrometheusConfigFactory.java, beekeeper-core/src/main/java/com/expediagroup/beekeeper/core/context/MonitoringContext.java, beekeeper-core/src/test/java/com/expediagroup/beekeeper/core/config/PrometheusConfigFactoryTest.java, beekeeper-integration-tests/src/test/java/com/expediagroup/beekeeper/integration/BeekeeperCleanupIntegrationTest.java, beekeeper-integration-tests/src/test/java/com/expediagroup/beekeeper/integration/BeekeeperPathSchedulerApiaryIntegrationTest.java, beekeeper-integration-tests/src/test/java/com/expediagroup/beekeeper/integration/model/SqsMessageFileTest.java, beekeeper-path-scheduler-apiary/src/main/java/com/expediagroup/beekeeper/scheduler/apiary/BeekeeperPathSchedulerApiary.java, beekeeper-path-scheduler-apiary/src/test/java/com/expediagroup/beekeeper/scheduler/BeekeeperPathSchedulerApiaryTest.java
Applying application tag to prometheus metrics, using composite meter in tests
=> Prometheus updates

CHANGELOG.md, Jenkinsfile
=> Update jenkins agent

CHANGELOG.md, beekeeper-core/src/main/java/com/expediagroup/beekeeper/core/model/HousekeepingEntity.java, beekeeper-core/src/main/java/com/expediagroup/beekeeper/core/model/HousekeepingMetadata.java, beekeeper-core/src/main/java/com/expediagroup/beekeeper/core/model/HousekeepingPath.java, beekeeper-core/src/main/java/com/expediagroup/beekeeper/core/repository/HousekeepingMetadataRepository.java, beekeeper-core/src/test/java/com/expediagroup/beekeeper/core/repository/HousekeepingMetadataRepositoryTest.java, beekeeper-core/src/test/java/com/expediagroup/beekeeper/core/repository/HousekeepingPathRepositoryTest.java, beekeeper-scheduler-apiary/src/main/java/com/expediagroup/beekeeper/scheduler/apiary/generator/ExpiredHousekeepingMetadataGenerator.java, beekeeper-scheduler-apiary/src/main/resources/db/migration/V2_1__Create_unpartitioned_table_housekeeping_table_and_alter_path_table_name_and_rename_path_status_column.sql, beekeeper-scheduler-apiary/src/test/java/com/expediagroup/beekeeper/scheduler/apiary/generator/ExpiredHousekeepingMetadataGeneratorTest.java, beekeeper-scheduler-apiary/src/test/java/com/expediagroup/beekeeper/scheduler/apiary/generator/HousekeepingEntityGeneratorTestBase.java, beekeeper-scheduler-apiary/src/test/java/com/expediagroup/beekeeper/scheduler/apiary/generator/UnreferencedHousekeepingPathGeneratorTest.java, beekeeper-scheduler-apiary/src/test/java/com/expediagroup/beekeeper/scheduler/apiary/messaging/MessageReaderAdapterTest.java, beekeeper-scheduler/src/main/java/com/expediagroup/beekeeper/scheduler/service/ExpiredHousekeepingMetadataSchedulerService.java, beekeeper-scheduler/src/main/java/com/expediagroup/beekeeper/scheduler/service/UnreferencedHousekeepingPathSchedulerService.java, beekeeper-scheduler/src/test/java/com/expediagroup/beekeeper/scheduler/service/ExpiredHousekeepingMetadataSchedulerServiceTest.java, beekeeper-scheduler/src/test/java/com/expediagroup/beekeeper/scheduler/service/UnreferencedHousekeepingPathSchedulerServiceTest.java
=> Add table expiry for partitioned tables

CHANGELOG.md, beekeeper-vacuum-tool/src/main/java/com/expediagroup/beekeeper/vacuum/BeekeeperVacuumToolApplication.java, beekeeper-vacuum-tool/src/test/java/com/expediagroup/beekeeper/vacuum/BeekeeperVacuumToolApplicationTest.java
=> Set lifecycle type for unreferenced paths

CHANGELOG.md, beekeeper-scheduler-apiary/src/main/java/com/expediagroup/beekeeper/scheduler/apiary/generator/utils/CleanupDelayExtractor.java
Really difficult change here, be careful reviewing the PR.
=> Changed log error to info in scheduler apiary

CHANGELOG.md
=> Update changelog to make release. TBD -> date

.github/workflows/main.yml, .github/workflows/release.yml, beekeeper-cleanup/pom.xml, pom.xml
Fixes #
- I cleaned pom.xml as there are some plugins already added in the parent pom.
- Added release.yml to publish to maven central.
- Upgrade localstack-utils dependency to fix S3 library.
=> Add release.yml and cleanup parent pom.xml

.github/workflows/release.yml
=> Change emil to eg-oss-ci

.github/workflows/release.yml
=> Add github token to push in github

.github/workflows/release.yml, beekeeper-api/pom.xml, beekeeper-cleanup/pom.xml, beekeeper-core/pom.xml, beekeeper-integration-tests/pom.xml, beekeeper-metadata-cleanup/pom.xml, beekeeper-path-cleanup/pom.xml, beekeeper-scheduler-apiary/pom.xml, beekeeper-scheduler/pom.xml, beekeeper-vacuum-tool/pom.xml, pom.xml
=> Downgrade project version 

.github/workflows/release.yml, pom.xml
I added the profile from the pom parent but adding a gpgConfiguration. I saw from different places that this maybe resolve the issue:
Links:
- Molten repository from Expedia Group: https://github.com/ExpediaGroup/molten/blob/master/pom.xml#L166
- First stack overflow issue: https://stackoverflow.com/questions/53992950/maven-gpg-plugin-failing-with-inappropriate-ioctl-for-device-when-running-unde
- Same issue but in Github Actions: https://github.com/samuelmeuli/action-maven-publish/issues/1
=> Add profile from parent adding gpgArguments

CHANGELOG.md, beekeeper-api/pom.xml, beekeeper-cleanup/pom.xml, beekeeper-core/pom.xml, beekeeper-integration-tests/pom.xml, beekeeper-metadata-cleanup/pom.xml, beekeeper-path-cleanup/pom.xml, beekeeper-scheduler-apiary/pom.xml, beekeeper-scheduler/pom.xml, beekeeper-vacuum-tool/pom.xml, pom.xml
=> Upgrade mockito

CHANGELOG.md, beekeeper-scheduler-apiary/src/main/resources/db/migration/V2_2__Add_index_for_housekeeping_path.sql
=> Add index for `housekeeping_path` table

.github/workflows/build.yml, .github/workflows/release.yml, CHANGELOG.md, beekeeper-cleanup/src/test/java/com/expediagroup/beekeeper/cleanup/aws/S3ClientTest.java, beekeeper-cleanup/src/test/java/com/expediagroup/beekeeper/cleanup/aws/S3DryRunPathCleanerTest.java, beekeeper-cleanup/src/test/java/com/expediagroup/beekeeper/cleanup/aws/S3PathCleanerTest.java, beekeeper-cleanup/src/test/java/com/expediagroup/beekeeper/cleanup/aws/S3SentinelFilesCleanerTest.java, beekeeper-cleanup/src/test/java/com/expediagroup/beekeeper/cleanup/hive/HiveMetadataCleanerTest.java, beekeeper-integration-tests/src/test/java/com/expediagroup/beekeeper/integration/BeekeeperMetadataCleanupIntegrationTest.java, beekeeper-metadata-cleanup/src/main/java/com/expediagroup/beekeeper/metadata/cleanup/context/CommonBeans.java, beekeeper-metadata-cleanup/src/test/java/com/expediagroup/beekeeper/metadata/cleanup/context/CommonBeansTest.java, beekeeper-path-cleanup/src/main/java/com/expediagroup/beekeeper/path/cleanup/context/CommonBeans.java, beekeeper-path-cleanup/src/test/java/com/expediagroup/beekeeper/path/cleanup/context/CommonBeansTest.java
enabling tests again for builds and releases, but disabling the ones which use localstack cause the issue hasn't been fixed yet
=> Enable tests except for localstack ones

CHANGELOG.md, beekeeper-core/src/main/java/com/expediagroup/beekeeper/core/repository/HousekeepingPathRepository.java
=> Remove order by from query

CHANGELOG.md, beekeeper-cleanup/src/main/java/com/expediagroup/beekeeper/cleanup/aws/S3PathCleaner.java, beekeeper-core/src/main/java/com/expediagroup/beekeeper/core/model/HousekeepingStatus.java, beekeeper-core/src/main/java/com/expediagroup/beekeeper/core/validation/S3PathValidator.java, beekeeper-core/src/test/java/com/expediagroup/beekeeper/core/validation/S3PathValidatorTest.java, beekeeper-integration-tests/src/test/java/com/expediagroup/beekeeper/integration/BeekeeperExpiredMetadataSchedulerApiaryIntegrationTest.java, beekeeper-integration-tests/src/test/java/com/expediagroup/beekeeper/integration/BeekeeperUnreferencedPathSchedulerApiaryIntegrationTest.java, beekeeper-metadata-cleanup/src/main/java/com/expediagroup/beekeeper/metadata/cleanup/handler/ExpiredMetadataHandler.java, beekeeper-metadata-cleanup/src/test/java/com/expediagroup/beekeeper/metadata/cleanup/handler/ExpiredMetadataHandlerTest.java, beekeeper-metadata-cleanup/src/test/java/com/expediagroup/beekeeper/metadata/cleanup/service/PagingMetadataCleanupServiceTest.java, beekeeper-path-cleanup/src/main/java/com/expediagroup/beekeeper/path/cleanup/handler/GenericPathHandler.java, beekeeper-path-cleanup/src/main/java/com/expediagroup/beekeeper/path/cleanup/handler/UnreferencedPathHandler.java, beekeeper-path-cleanup/src/test/java/com/expediagroup/beekeeper/path/cleanup/handler/GenericPathHandlerTest.java, beekeeper-path-cleanup/src/test/java/com/expediagroup/beekeeper/path/cleanup/service/PagingCleanupServiceTest.java, beekeeper-scheduler-apiary/src/main/java/com/expediagroup/beekeeper/scheduler/apiary/generator/ExpiredHousekeepingMetadataGenerator.java, beekeeper-scheduler-apiary/src/main/java/com/expediagroup/beekeeper/scheduler/apiary/generator/UnreferencedHousekeepingPathGenerator.java, beekeeper-scheduler-apiary/src/main/java/com/expediagroup/beekeeper/scheduler/apiary/messaging/MessageReaderAdapter.java, beekeeper-scheduler-apiary/src/test/java/com/expediagroup/beekeeper/scheduler/apiary/generator/ExpiredHousekeepingMetadataGeneratorTest.java, beekeeper-scheduler-apiary/src/test/java/com/expediagroup/beekeeper/scheduler/apiary/generator/HousekeepingEntityGeneratorTestBase.java, beekeeper-scheduler-apiary/src/test/java/com/expediagroup/beekeeper/scheduler/apiary/generator/UnreferencedHousekeepingPathGeneratorTest.java
=> Add path checks before scheduling and before deletion

CHANGELOG.md, beekeeper-cleanup/pom.xml, beekeeper-metadata-cleanup/pom.xml, beekeeper-path-cleanup/pom.xml, beekeeper-scheduler-apiary/pom.xml, pom.xml
=> fix: added aws-sts-jdk to solve irsa assume role issue

beekeeper-integration-tests/pom.xml, beekeeper-integration-tests/src/test/java/com/expediagroup/beekeeper/integration/BeekeeperExpiredMetadataSchedulerApiaryIntegrationTest.java, beekeeper-integration-tests/src/test/java/com/expediagroup/beekeeper/integration/BeekeeperMetadataCleanupIntegrationTest.java, beekeeper-integration-tests/src/test/java/com/expediagroup/beekeeper/integration/BeekeeperPathCleanupIntegrationTest.java, beekeeper-integration-tests/src/test/java/com/expediagroup/beekeeper/integration/BeekeeperUnreferencedPathSchedulerApiaryIntegrationTest.java
Changing visibility of integration test vars and methods to protected to allow the classes to be extended.
=> Change integration test visibility to protected

CHANGELOG.md, beekeeper-scheduler-apiary/src/main/java/com/expediagroup/beekeeper/scheduler/apiary/generator/ExpiredHousekeepingMetadataGenerator.java, beekeeper-scheduler-apiary/src/test/java/com/expediagroup/beekeeper/scheduler/apiary/generator/ExpiredHousekeepingMetadataGeneratorTest.java, beekeeper-scheduler/src/main/java/com/expediagroup/beekeeper/scheduler/hive/HiveClient.java, beekeeper-scheduler/src/test/java/com/expediagroup/beekeeper/scheduler/hive/hive/HiveClientTest.java
=> fix: use partition create time

CHANGELOG.md, beekeeper-api/pom.xml, beekeeper-metadata-cleanup/pom.xml, beekeeper-path-cleanup/pom.xml, beekeeper-scheduler-apiary/pom.xml, pom.xml
=> fix: add multiplatform support
